// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB_Dp2DlvchDu0Zl5R21yJXSVqlkiiLbY',
    appId: '1:1089004613765:web:94ea429172b1fb0ce1b9ec',
    messagingSenderId: '1089004613765',
    projectId: 'flocksync-dcc08',
    authDomain: 'flocksync-dcc08.firebaseapp.com',
    storageBucket: 'flocksync-dcc08.firebasestorage.app',
    measurementId: 'G-SHZHCDMFCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX-gJ5a_f9P_8bRSurnSwCvfA6XHjHJfs',
    appId: '1:1089004613765:android:7a334aff0e074c56e1b9ec',
    messagingSenderId: '1089004613765',
    projectId: 'flocksync-dcc08',
    storageBucket: 'flocksync-dcc08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIUyuTnnYQJVb7uXNc4Ca0D2iI7X1nLEM',
    appId: '1:1089004613765:ios:0f11db422fce1f78e1b9ec',
    messagingSenderId: '1089004613765',
    projectId: 'flocksync-dcc08',
    storageBucket: 'flocksync-dcc08.firebasestorage.app',
    androidClientId: '1089004613765-vaummfkvgjqgv6s3u7u021g7o7gi78o7.apps.googleusercontent.com',
    iosClientId: '1089004613765-10c0qnhfplkrujh16uber3gu53mjijdh.apps.googleusercontent.com',
    iosBundleId: 'com.flocksync.flocksync',
  );

}